from groq import Groq
import os

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def generate_response(prompt: str):
    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            # {
            #     "role": "system",
            #     "content": "Return only valid JSON."
            # },
            {
                "role": "user",
                "content": prompt
            }
        ],
        #This will stream the LLM response as it is generated in real time rather than send the entire response after completion        
        stream=True # Adding streaming response instead of plain text response. 
    )
    # return response.choices[0].message.content.strip()
    #This generator sends the chunks generated by LLM to streaming response
    for chunk in response:
         text = chunk.choices[0].delta.content
         if text:
                yield text